# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1201da65ac2a921cc0aeea896d8d259563e6f220eabf065ac6d545b142472bf9b7c2efdce33cb9a2358a85d5537171e24ff85cf7a6e50d56fb96520d189b6cab

test:
  secret_key_base: 05573379cf7f6303efe9dfa697ac13050757c0e6aa6c3518c99693814d3938198dbec68298c40cfa535da9bf352170f0291ab43608a85a5499a9f6a7e2a62885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
